baseURL = "http://sophieli.com.au"
languageCode = "en-us"
title = "Sophie Li"
theme = "dimension"

[params]
  description = '<!--[-->Fullstack Developer| Go-Getter | Puppy-Lover <!--]-->'
  logo = "fa-code"

[[params.social]]
  icon = "fab fa-linkedin"
  link = "https://www.linkedin.com/in/sophiecli/"
  medium = 'LinkedIn'

[[params.social]]
  icon = "fab fa-github-alt"
  link = "https://github.com/Sophiecli"
  medium = "GitHub"

[languages]
[languages.en]
languageName = "English"
weight = 1
